[package]
name = "klaptik"
description = "Experimental UI rendering framework for `no_std` targets"
authors = ["Vitaly Domnikov <oss@vitaly.codes>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/dotcypress/klaptik"
version = "0.0.3"

[dependencies]
paste = "1.0.9"

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.6"